Preparation IH
OpenSourcePolitics/decidim-pvl pull request #5
Opened 2023-05-05 14:52 UTC by eliegaboriau

#### :tophat: Description
*Please describe your pull request.*

#### :pushpin: Related Issues
*Link your PR to an issue*
- Related to #?
- Fixes #?
- [Notion card]()

#### Testing
*Describe the best way to test or validate your PR.*

Example:
* Log in as admin
* Access Backoffice
* Go to organization settings
* See ...

#### Tasks
- [ ] Add specs
- [ ] Add note about overrides in OVERLOADS.md

### :camera: Screenshots
*Please add screenshots of the changes you're proposing if related to the UI*

2023-05-05 15:29 UTC, armandfardeau approved these changes

2023-05-09 13:11 UTC, Quentinchampenois requested changes
I just saw `sidekiq` dependencies are not pinned and will cause a crash at runtime

2023-05-09 13:11 UTC, Quentinchampenois commented on Gemfile
>    gem "sidekiq"
We must pin `sidekiq` and `sidekiq-scheduler` to prevent crash on Sidekiq : 

Cf: https://github.com/OpenSourcePolitics/decidim-app/pull/291

2023-05-11 21:04 UTC, armandfardeau approved these changes

2023-05-12 08:17 UTC, Quentinchampenois approved these changes

2023-05-15 12:38 UTC, armandfardeau approved these changes

2023-05-15 15:20 UTC, merged